#!/usr/bin/env python3
"""Expand kb.source.json into ChopsticksAIKB.swift for the macOS app."""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SOURCE = HERE / "kb.source.json"
SWIFT_OUT = HERE.parent / "Sources" / "ChopsticksAIKB.swift"

STOPWORDS = {
    "a", "an", "and", "are", "at", "be", "by", "can", "did", "do", "does", "for",
    "from", "get", "got", "has", "have", "how", "i", "if", "in", "is", "it", "its",
    "me", "my", "no", "not", "of", "on", "or", "so", "the", "then", "there", "this",
    "to", "up", "use", "was", "what", "when", "where", "which", "who", "why", "will",
    "with", "you", "your",
}

MIN_TERM_LEN = 3

ADJACENT = {
    "a": "qws", "b": "vgn", "c": "xdv", "d": "serfcx", "e": "wsdr", "f": "drtgvc",
    "g": "ftyhbv", "h": "gyujnb", "i": "ujko", "j": "huikmn", "k": "jiolm",
    "l": "kop", "m": "njk", "n": "bhjm", "o": "iklp", "p": "ol", "q": "wa",
    "r": "edft", "s": "awedxz", "t": "rfgy", "u": "yhji", "v": "cfgb",
    "w": "qase", "x": "zsdc", "y": "tghu", "z": "asx",
}


def normalise(text: str) -> str:
    text = text.lower()
    text = re.sub(r"[^a-z0-9\s]+", " ", text)
    return re.sub(r"\s+", " ", text).strip()


def expand_term(term: str) -> list[str]:
    out = {term}
    if " " in term:
        return list(out)
    if len(term) >= MIN_TERM_LEN:
        for i, ch in enumerate(term):
            for adj in ADJACENT.get(ch, ""):
                typo = term[:i] + adj + term[i + 1 :]
                if len(typo) >= MIN_TERM_LEN:
                    out.add(typo)
    return list(out)


def build():
    raw = json.loads(SOURCE.read_text(encoding="utf-8"))
    intents = []
    authored = expanded = 0
    products = set()
    for it in raw["intents"]:
        products.add(it["product"])
        terms = []
        seen = set()
        for phrase, weight in it["terms"]:
            authored += 1
            for t in expand_term(normalise(phrase)):
                if t in seen or t in STOPWORDS or len(t) < MIN_TERM_LEN:
                    continue
                seen.add(t)
                terms.append((t, weight))
                expanded += 1
        intents.append({**it, "terms": terms})
    kb = {"meta": raw["meta"], "intents": intents}
    stats = {
        "intents": len(intents),
        "authored": authored,
        "expanded": expanded,
        "products": sorted(products),
    }
    return kb, stats


def swift_string(s: str) -> str:
    return json.dumps(s, ensure_ascii=False)


def emit_swift(kb: dict) -> str:
    lines = [
        "// Generated by kb/build-kb.py - do not edit by hand.",
        "",
        "struct ChopsticksAIIntent {",
        "    let id: String",
        "    let product: String",
        "    let label: String",
        "    let priority: Int",
        "    let answer: String",
        "    let terms: [(String, Int)]",
        "}",
        "",
        "enum ChopsticksAIKB {",
        f"    static let tagline = {swift_string(kb['meta']['tagline'])}",
        f"    static let version = {swift_string(kb['meta']['version'])}",
        "    static let intents: [ChopsticksAIIntent] = [",
    ]
    for it in kb["intents"]:
        terms = ", ".join(f"({swift_string(t)}, {w})" for t, w in it["terms"])
        lines += [
            "        ChopsticksAIIntent(",
            f"            id: {swift_string(it['id'])},",
            f"            product: {swift_string(it['product'])},",
            f"            label: {swift_string(it['label'])},",
            f"            priority: {it['priority']},",
            f"            answer: {swift_string(it['answer'])},",
            f"            terms: [{terms}]",
            "        ),",
        ]
    lines += ["    ]", "}", ""]
    return "\n".join(lines)


def main() -> None:
    args = set(sys.argv[1:])
    kb, stats = build()

    if "--stats" in args or "--check" in args:
        print(f"intents        : {stats['intents']}")
        print(f"authored terms : {stats['authored']}")
        print(f"expanded terms : {stats['expanded']}")
        print(f"products       : {', '.join(stats['products'])}")

    if "--check" in args:
        print("check passed - nothing written")
        return

    SWIFT_OUT.write_text(emit_swift(kb), encoding="utf-8")
    print(f"wrote {SWIFT_OUT.relative_to(HERE.parent)} ({SWIFT_OUT.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
